version: '3.1'

services:

  db:
    image: postgres
    restart: always
    container_name: seetask_db
    environment:
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_USER: $POSTGRES_USER
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - seetask

  php-fpm:
    build:
      context: ./config/php
    depends_on:
      - db
    ports:
      - "23:22"
    volumes:
      - ./../../:/var/www
      - ./config/php/php.ini:/usr/local/etc/php/php.ini
    networks:
      - seetask

  nginx:
    image: nginx
    volumes:
      - ./../../:/var/www
      - ./config/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php-fpm
    ports:
      - "443:443"
      - "80:80"
    networks:
      - seetask

networks:
  seetask:
    driver: bridge