CREATE TABLE project (
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name varchar(255) NOT NULL,
    description text NULL,
    status varchar(25) NOT NULL,
    createDateTime timestamp DEFAULT now(),
    userId integer,
    FOREIGN KEY (userId) REFERENCES users (id) ON DELETE SET NULL
)